name: 'bookmarker-quarkus'
services:
  bookmarker-db:
    image: postgres:17-alpine
    container_name: bookmarker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  bookmarker-quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: bookmarker-quarkus
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://bookmarker-db:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - bookmarker-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024m