insert into categories(id, name, slug) values
                                           (1, 'General', 'general'),
                                           (2, 'Java', 'java'),
                                           (3, 'Spring', 'spring'),
                                           (4, 'Hibernate', 'hibernate'),
                                           (5, 'JPA', 'jpa'),
                                           (6, 'Spring Boot', 'spring-boot'),
                                           (7, 'Spring Data', 'spring-data'),
                                           (8, 'Spring Security', 'spring-security'),
                                           (9, 'Spring Cloud', 'spring-cloud'),
                                           (10, 'Spring WebFlux', 'spring-webflux'),
                                           (11, 'Quarkus', 'quarkus'),
                                           (12, 'Kotlin', 'kotlin'),
                                           (13, 'Gradle', 'gradle'),
                                           (14, 'Maven', 'maven'),
                                           (15, 'Docker', 'docker'),
                                           (16, 'Kubernetes', 'kubernetes'),
                                           (17, 'AWS', 'aws'),
                                           (18, 'Micronaut', 'micronaut'),
                                           (19, 'IntelliJ IDEA', 'intellij-idea');

insert into bookmarks(id, title, url, description, created_at, updated_at) values
                                                                               (1, 'Geovannycode Blog', 'https://geovannycode.com', 'Geovannycode Blog', current_timestamp, current_timestamp),
                                                                               (2, 'Geovannycode YouTube Channel', 'https://youtube.com/geovannycode', 'Geovannycode YouTube Channel', current_timestamp, current_timestamp),
                                                                               (3, 'Geovannycode X', 'https://x.com/geovannycode', 'Geovannycode X', current_timestamp, current_timestamp),
                                                                               (4, 'IntelliJ IDEA Blog', 'https://blog.jetbrains.com/idea/', 'IntelliJ IDEA Blog', current_timestamp, current_timestamp),
                                                                               (5, 'JetBrains Blog', 'https://blog.jetbrains.com/', 'JetBrains Blog', current_timestamp, current_timestamp),
                                                                               (6, 'JetBrains Junie', 'https://www.jetbrains.com/junie/', 'JetBrains Junie: Your smart coding agent', current_timestamp, current_timestamp),
                                                                               (7, 'JetBrains Academy', 'https://www.jetbrains.com/academy/', 'JetBrains Academy', current_timestamp, current_timestamp),
                                                                               (8, 'Carbon', 'https://carbon.now.sh/', 'Carbon: Create and share beautiful images of your source code', current_timestamp, current_timestamp),
                                                                               (9, 'AI Native Dev Landscape', 'https://ainativedev.io/landscape', 'AI Native Dev Landscape', current_timestamp, current_timestamp),
                                                                               (10, 'Spring Initializr', 'https://start.spring.io/', 'Spring Initializr', current_timestamp, current_timestamp),
                                                                               (11, 'Quarkus Project Generator', 'https://quarkus.io/', 'Quarkus Project Generator', current_timestamp, current_timestamp),
                                                                               (12, 'Micronaut Launch', 'https://micronaut.io/launch/', 'Micronaut Launch', current_timestamp, current_timestamp),
                                                                               (13, 'Vaadin Project Generator', 'https://start.vaadin.com/', 'Vaadin Project Generator', current_timestamp, current_timestamp);
